input:
    log_table : "lookalike_03042021_logs"
    did_table: "lookalike_03042021_trainready"
    keywords_table: "din_ad_keywords_09172020"
    test_table: "lookalike_trainready_jimmy_test"
    din_model_tf_serving_url: "http://10.193.217.105:8506/v1/models/lookalike3:predict"
    din_model_length: 20
    seeduser_table : "lookalike_seeduser"
    number_of_seeduser: 1000
    extend: 2000
output:
    did_score_table: "lookalike_score_01112021"
    did_score_table_norm:  "lookalike_score_norm_01112021"
    similarity_table: "lookalike_similarity"